#!/bin/bash
sudo amazon-linux-extras install java-openjdk11 -y
cd /opt
sudo wget https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
sudo tar -xvzf apache-maven-3.8.4-bin.tar.gz
sudo mv apache-maven-3.8.4-bin maven
